from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.pdfbase import pdfmetrics

from datetime import datetime
import pandas as pd


def create_pdf(df):

    doc = SimpleDocTemplate(
        "Airbnb_Analytics_Report.pdf"
    )

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    h2 = styles["Heading2"]
    body = styles["BodyText"]

    story = []

    # ====================================================
    # COVER PAGE
    # ====================================================

    story.append(
        Paragraph(
            "<font color='darkblue'><b>Airbnb Data Engineering Report</b></font>",
            title
        )
    )

    story.append(Spacer(1,25))

    story.append(
        Paragraph(
            "<b>Singapore Airbnb Analytics Dashboard</b>",
            h2
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "Generated by : <b>Dinali Chamodya</b>",
            body
        )
    )

    story.append(
        Paragraph(
            f"Generated Date : {datetime.now().strftime('%d %B %Y %H:%M')}",
            body
        )
    )

    story.append(PageBreak())

    # ====================================================
    # KPI SUMMARY
    # ====================================================

    story.append(
        Paragraph(
            "Dashboard Summary",
            h2
        )
    )

    story.append(Spacer(1,12))

    data = [

        ["Metric","Value"],

        ["Total Listings",len(df)],

        ["Average Price",
         f"${df['price'].mean():.2f}"],

        ["Average Rating",
         f"{df['review_scores_rating'].mean():.2f}"],

        ["Average Occupancy",
         f"{df['occupancy_rate'].mean():.2f}%"]

    ]

    table = Table(data,colWidths=[220,180])

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("BOTTOMPADDING",(0,0),(-1,0),10)

        ])

    )

    story.append(table)

    story.append(Spacer(1,25))

    # ====================================================
    # BAR CHART
    # ====================================================

    story.append(
        Paragraph(
            "Average Price by Room Type",
            h2
        )
    )

    avg = df.groupby("room_type")["price"].mean()

    drawing = Drawing(420,240)

    chart = VerticalBarChart()

    chart.x = 40
    chart.y = 30
    chart.height = 160
    chart.width = 300

    chart.data = [list(avg.values)]

    chart.categoryAxis.categoryNames = list(avg.index)

    chart.valueAxis.valueMin = 0

    chart.bars[0].fillColor = colors.darkblue

    drawing.add(chart)

    story.append(drawing)

    story.append(PageBreak())

    # ====================================================
    # HYPOTHESIS
    # ====================================================

    story.append(
        Paragraph(
            "Hypothesis Testing",
            h2
        )
    )

    hypo = [

        ["Hypothesis","Result"],

        ["H1",
         "Accepted - Entire homes are significantly more expensive"],

        ["H2",
         "Accepted - Superhosts receive higher ratings"],

        ["H3",
         "Accepted - Reviews significantly affect prices"],

        ["H4",
         "Accepted - Prices differ across neighbourhoods"]

    ]

    t = Table(hypo,colWidths=[80,360])

    t.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,1),(-1,-1),colors.beige)

        ])

    )

    story.append(t)

    story.append(Spacer(1,25))

    # ====================================================
    # BUSINESS INSIGHTS
    # ====================================================

    story.append(
        Paragraph(
            "Business Insights",
            h2
        )
    )

    insights = [

        "• Entire home/apartment listings generate the highest revenue.",

        "• Superhosts consistently achieve higher customer ratings.",

        "• River Valley and Orchard are premium neighbourhoods.",

        "• Hotel rooms have higher average prices than private rooms.",

        "• Listings with more reviews generally maintain higher ratings."

    ]

    for item in insights:

        story.append(
            Paragraph(item,body)
        )

        story.append(Spacer(1,8))

    story.append(Spacer(1,20))

    story.append(

        Paragraph(

            "<b>End of Report</b>",

            h2

        )

    )

    doc.build(story)